[package]
name = "discv5"
edition = "2018"
version = "0.1.0-alpha"
description = "Implementation of the p2p discv5 discovery protocol"
authors = ["Age Manning <Age@AgeManning.com>"]
license = "MIT"
repository = "https://github.com/sigp/discv5"
keywords = ["peer-to-peer", "libp2p", "networking", "discovery", "discv5"]
categories = ["network-programming", "asynchronous"]

[dependencies]
libsecp256k1 = "0.3.5"
#libp2p-core = { version = "0.13.1", path = "../../core" }
#libp2p-swarm = { version = "0.3.0", path = "../../swarm" }
#multiaddr = { package = "parity-multiaddr", version = "0.6.0", path = "../multiaddr" }
# multihash = { package = "parity-multihash", version = "0.2.0", path = "../../misc/multihash" }
enr = { version = "0.1.0-alpha.5", features = ["libsecp256k1", "ed25519"] }
futures = "0.3.4"
bigint = "4.4.1"
log = "0.4.8"
rlp = "0.4.5"
sha2 = "0.8.1"
hkdf = "0.8.0"
zeroize = "1.1.0"
openssl = "0.10.29"
hex = "0.4.2"
fnv = "1.0.6"
arrayvec = "0.5.1"
digest = "0.8.1"
rand = "0.7.3"
async-std = "1.5.0"
tokio = { version = "0.2.19", features = ["time"] }

[dev-dependencies]
#libp2p-secio = { version = "0.13.0", path = "../../protocols/secio" }
#libp2p-yamux = { version = "0.13.0", path = "../../muxers/yamux" }
#libp2p-tcp = { version = "0.13.0", path = "../../transports/tcp" }
quickcheck = "0.9.2"
env_logger = "0.7.1"
simple_logger = "1.6.0"
tokio = "0.2.19"
rand_xorshift = "0.2.0"
rand_core = "0.5.1"
